apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: observability
stringData:
    SECRET_NFS_SERVER: ENC[AES256_GCM,data:3dOPOFwb0oS7zy84A9k=,iv:u/KNal2ie0k8E8dwCcT5/BcPOWPRneQkvP/NQ4UuM5g=,tag:J4XSyMaO6S+yeNeNvts31g==,type:str]
    SECRET_NFS_PATH: ENC[AES256_GCM,data:jy0YNBxf5ZlBy5M5MLwRWkHFCJP+EFtFMg==,iv:FlHdvK+ZswAj+nuhp0u0uKIyr1Km5Kj+sqKcavrzi/I=,tag:udARqujC96oxV5UogsGeEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cqnxcuzntxkukm5h3pzwh5cupuy40z6wazdnwfzk9wk9z7ksgsdq8hwvuc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoL1NnRDVYTEF2Nm51MW1C
            aUd1RDR6QXRIWUlJWjFWQ3RTUS9PeWlaUVRFCmE0WDVERlY0QXBjM1g2NHVYem4z
            Nk9YNGZPOG9ja2VScGlsL0Myd3NGaVEKLS0tIHZXZWNzdWhUbWxQNjJFeDBiamN2
            ak5IQXdqWHpoSk54VHp3WE1CdkVRY1kKyhEjvZYu/qO2VHotOCKMXpqlpevv+1lk
            CdZWErcM31ncmVZZhoJ/5Scz8ImaBfJeVUugzuXXGplDc7L4cDvaZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-02T22:00:29Z"
    mac: ENC[AES256_GCM,data:vsdSq9YMaxf+8HKAEn8eH9EqPY/9Xigt+OFTiJH9Ml+8QjCLSQUGaGocCq9YYmBKACZwyXZNFxCcF4/ZEWcuwUm/k3WDqQz+i4jnEKWZXrgrMQbhP4EOZPTPfMulnjg21mhWLBtt2yWqm9CKjlPZxepHSCICjw8XwoRenIwJWMg=,iv:sXZ8IF5epqShoeWmtvkZIGFanOciy9y59WD05W0HolQ=,tag:EecDDVNCRbHhew469zrLUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
