---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  nfs:
    path: ${SECRET_NFS_PATH}/prometheus-pv
    server: ${SECRET_NFS_SERVER}
    persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: prometheus-pvc
    namespace: observability
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: observability
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  nfs:
    path: ${SECRET_NFS_PATH}/alertmanager-pv
    server: ${SECRET_NFS_SERVER}
    persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: alertmanager-pvc
    namespace: observability
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-pvc
  namespace: observability
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
