apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:LV/7JginXmrZiA==,iv:whYiJsSKEVw5XVoGUD9WS4lJMKsPVdac/E0hy8YRUmE=,tag:yz4sB62FUg8w2droBx+KXA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:z12HSN2iTB2hqZPeR84rXGeP,iv:/mlvR6Q4KKW/lcN5GIXiBlKCFn5j+N2SCsuj05JJQ5I=,tag:bvpgp7PqpKApOYYaPMhijw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:3DFlpCNaGkGJI+cYVSGUf1yvKD2bb/NVylqD7hWhRfn8xZDu,iv:Y+nlW4grQUW/PkqEeZZ0AH7CKMtFXd5wVm7LwZspI/w=,tag:GpHKHZbObx8rn45ywQRPEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cqnxcuzntxkukm5h3pzwh5cupuy40z6wazdnwfzk9wk9z7ksgsdq8hwvuc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZlloMWVid1RxRzcvTG9O
            WHdjVzI4a1BmQ1hqNHFaWHJLZUpyMHMrZlJZCmNDd0s3ajU0d2lMNHZjS0hDRXl3
            OTE3MzF3QXFFZG1XaThjWEpkejVoMncKLS0tIGc0TGhBR0pYYUNZbHAwWFkxYlRa
            cWNvblV1ME9TcVl4U05MSjJSTjQrU28KrtICJ4yqbNm2XxK/fOqpd1z8/j4Ay6P+
            vroFCa4T5yvDquwqlIeqFETFPjHZshfvTULdPttVlftRwPYHfJDcdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-24T21:06:29Z"
    mac: ENC[AES256_GCM,data:/VB7/XVub3Lzc+EPFK8eqQeO34RDGGSV0nAqESueiQtSzl+abFDMa1OM7yiND4UgFxQxadYRaddTwKdCrUFVHGSGnzcxo6OnD/xCsh7BoCQSWzuFS2eFIrX0UwTF+NgbJizIl+L+IaSL6xqYwLmnyPkNwDWN50bWElza9AtQVtU=,iv:XittkQRMu+mm2tFJsgdQoV2qXS7V6WvaHSmNYqfPmGo=,tag:Mrtj1E7Ga6U+MmMw02E3vw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
