apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cqnxcuzntxkukm5h3pzwh5cupuy40z6wazdnwfzk9wk9z7ksgsdq8hwvuc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWEdFckRBb21zb1NUZVcx
            UysxZzVHVFBjZVV5VW1oYzVqRlhtbFpIRVdVCnVqdndyYit3OXVmOHNneXcyei9i
            ajN6cE16b09UWHh4bjdOVVlYY2RrUUkKLS0tIDZubkRseUpqT1JFWTJCd2x2WlJz
            cDFCeXZwemVHT2Z5T25NVG16ZHFEbVUKmO7I1OBkmsnttRggQ2fW/ZTeqpQj5b6n
            GoB7JhLZa9s5Tgw0HnkOyn+1tNsbhEL6j+nSwR3otbc8tVWrfGm0fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-24T20:26:55Z"
    mac: ENC[AES256_GCM,data:HI7L4LNB/Ww4zoaJhlDEci7sQL7r063uOI/VstIST1GI3A8PdQC25hVx51A03iHXmQ9qXucOY2lRWehbgQC/pQTgVhyyGH29sWw2doJyzktu7IKwCpxUA42P68+8MLsxl7Doto0mSrGXH2Zt6867S3LUiAUsjtyedSUAYtMBdKw=,iv:XEZa9CugywIiHhIQim36ijvEAHmTIPgzfK2k7BPfA0g=,tag:4mfIwTw2ZRUXEiZXLEX0qQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
